apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
spec:
  sourceFormat: unstructured
  git:
    dir: project-syncs/dev-primary-002
    auth: none
    branch: master
    repo: https://github.com/Manny2014/kcc-root