apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  mode: cluster
  googleServiceAccount: kcc-sa@kcc-root-01.iam.gserviceaccount.com # TODO: THIS WILL CHANGE WHEN KCC-ROOT IS DELETED/RECREATED