apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: cs-app-svcs-sa
  namespace: config-control
  annotations:
    configsync.gke.io/cluster-selector: select-kcc-root
spec:
  displayName: ConfigSync AppServices SA
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cs-app-svcs-sa-wi
  namespace: config-control
  annotations:
    configsync.gke.io/cluster-selector: select-kcc-root
spec:
  member: serviceAccount:kcc-root.svc.id.goog[config-management-system/root-reconciler]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: cs-app-svcs-sa