apiVersion: eventarc.cnrm.cloud.google.com/v1beta1
kind: EventarcTrigger
metadata:
  name: eventarctrigger-sample
  labels:
    foo1: bar1
spec:
  location: us-central1
  destination:
    cloudRunService:
      serviceRef:
        external: eventarctrigger-dep
      region: us-central1
  serviceAccountRef:
    name: eventarctrigger-dep
  transport:
    pubsub:
      topicRef:
        name: eventarctrigger-dep
  matchingCriteria:
  - attribute: "type"
    value: "google.cloud.pubsub.topic.v1.messagePublished"