apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  labels:
    kcc: works
  annotations: 
    # TODO: WHY CAN'T REF RESOURCE?
    cnrm.cloud.google.com/project-id: "net-dev-host-vpc"
  name: dev-net
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: us-central1-0
  annotations: 
    # TODO: WHY CAN'T REF RESOURCE?
    # --> WILL BE SOLVED IN NS IS THE PROJECT NAME
    cnrm.cloud.google.com/project-id: "net-dev-host-vpc"
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-central1
  description: US Central subnet 0
  privateIpGoogleAccess: true
  networkRef:
    name: dev-net
  secondaryIpRange:
  - ipCidrRange: 172.16.0.0/19
    rangeName: us-central1-0-scidr-0
  - ipCidrRange: 172.16.32.0/19
    rangeName: us-central1-0-scidr-32
  - ipCidrRange: 172.16.64.0/19
    rangeName: us-central1-0-scidr-64
  - ipCidrRange: 172.16.96.0/19
    rangeName: us-central1-0-scidr-96
  - ipCidrRange: 172.16.128.0/19
    rangeName: us-central1-0-scidr-128
  - ipCidrRange: 172.16.160.0/19
    rangeName: us-central1-0-scidr-160
  - ipCidrRange: 172.16.192.0/19
    rangeName: us-central1-0-scidr-192
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: us-central1-1
  annotations: 
    # TODO: WHY CAN'T REF RESOURCE?
    # --> WILL BE SOLVED IN NS IS THE PROJECT NAME
    cnrm.cloud.google.com/project-id: "net-dev-host-vpc"
spec:
  ipCidrRange: 10.3.0.0/16
  region: us-central1
  description: US Central subnet 1
  privateIpGoogleAccess: true
  networkRef:
    name: dev-net
  secondaryIpRange:
  - ipCidrRange: 172.17.0.0/19
    rangeName: us-central1-1-scidr-0
  - ipCidrRange: 172.17.32.0/19
    rangeName: us-central1-1-scidr-32
  - ipCidrRange: 172.17.64.0/19
    rangeName: us-central1-1-scidr-64
  - ipCidrRange: 172.17.96.0/19
    rangeName: us-central1-1-scidr-96
  - ipCidrRange: 172.17.128.0/19
    rangeName: us-central1-1-scidr-128
  - ipCidrRange: 172.17.160.0/19
    rangeName: us-central1-1-scidr-160
  - ipCidrRange: 172.17.192.0/19
    rangeName: us-central1-1-scidr-192
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: net-dev-host-vpc
  name: egress-internet
spec:
  allow:
  - protocol: all
  destinationRanges:
  - 0.0.0.0/0
  direction: EGRESS
  networkRef:
    name: dev-net
  priority: 65535 # 0 -> Highest Priority, 65535 -> Lowest Priority 
  resourceID: egress-internet
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: net-dev-host-vpc
  name: default-allow-internal
spec:
  allow:
  - protocol: all
  direction: INGRESS
  networkRef:
    name: dev-net
  priority: 65535
  resourceID: default-allow-internal
  sourceRanges:
  - 10.2.0.0/16
  - 10.3.0.0/16
  - 172.16.0.0/16
  - 172.17.0.0/16