apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  labels:
    kcc: works
  annotations: 
    # TODO: WHY CAN'T REF RESOURCE?
    cnrm.cloud.google.com/project-id: "net-dev-host-vpc"
  name: dev-net
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: us-central1-0
  annotations: 
    # TODO: WHY CAN'T REF RESOURCE?
    # --> WILL BE SOLVED IN NS IS THE PROJECT NAME
    cnrm.cloud.google.com/project-id: "net-dev-host-vpc"
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-central1
  description: US Central subnet 0
  privateIpGoogleAccess: true
  networkRef:
    name: dev-net
  secondaryIpRange:
  - ipCidrRange: 172.16.0.0/19
    rangeName: us-central1-0-scidr-0
  - ipCidrRange: 172.16.0.0/32
    rangeName: us-central1-0-scidr-32
  - ipCidrRange: 172.16.0.0/64
    rangeName: us-central1-0-scidr-64
  - ipCidrRange: 172.16.0.0/96
    rangeName: us-central1-0-scidr-96
  - ipCidrRange: 172.16.0.0/128
    rangeName: us-central1-0-scidr-128
  - ipCidrRange: 172.16.0.0/160
    rangeName: us-central1-0-scidr-160
  - ipCidrRange: 172.16.0.0/192
    rangeName: us-central1-0-scidr-192
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA