resources: 
- ns.yaml
- project.yaml
- repo-sync.yaml

namespace: dev-host-vpc

patchesJson6902:
- target:
    group: "resourcemanager.cnrm.cloud.google.com" 
    version: v1beta1
    kind: Project
    name: ".*"
  patch: |-
    - op: add
      path: /spec/folderRef
      value:
        name: net-dev