resources:
- f-net-dev.yaml

namespace: net-services

patchesJson6902:
- target:
    group: "resourcemanager.cnrm.cloud.google.com" 
    version: v1beta1
    kind: Folder
    name: ".*"
  patch: |-
    - op: add
      path: /spec/folderRef
      value:
        name: net-services