apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: eventarctrigger-dep
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  launchStage: "GA"
  location: us-central1
  template:
    containers:
      - env:
          - name: "FOO"
            value: "BAR"
        image: "gcr.io/cloudrun/hello"
    scaling:
      maxInstanceCount: 2
  traffic:
    - percent: 100
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"