# See: https://cloud.google.com/config-connector/docs/reference/resource-docs/resourcemanager/project#project_in_folder
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/auto-create-network: "false"
  labels:
    environment: development
  name: ej-playground-001
spec:
  name: Playground Project
  folderRef:
    name: development
  billingAccountRef:
    # Replace "${BILLING_ACCOUNT_ID?}" with the numeric ID for your billing account
    external: "01446E-E7CA2C-85746A"